language: go

go:
  - 1.9
  - tip

before_install:
  - go get -t -v ./...

script:
  - cd http
  - chmod +x hook_tests.sh
  - ./hook_tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
